apiVersion: apps/v1
kind: Deployment
metadata:
  name: publish-management-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publish-management
  template:
    metadata:
      labels:
        app: publish-management
    spec:
      containers:
      - name: publish-management-container
        image: iamberkesahin/publish-management:latest
        ports:
        - containerPort: 8080